### ISSUE TITLE
Why does it expect newlines?

### ISSUE THREAD

**Issue by HaloZero** [Cue/ocstyle#2]
So I was looking at your example and I'm confused about something

So I copied in the text for test.m and kept fixing things until it ended up being this
@implementation SomeClass
- (void)someMessage:(NSString *)subdomain {
  NSString *shouldStartLowerCase;
  }

@end

But then you get the error

ERROR: 3:43 [69] - MissingNewline - Should have newline after ;
ERROR: 3:43 [69] - MissingSemicolon - Expected a semicolon

Does it think that the .m file is a .h file or am I missing some kinda style that I don't fully comprehend here?

**Comment by robbywalker** [comment]
We use this style for message implementations:

``` objc
- (void)someMessage:(NSString *)subdomain;
{
  // code
}
```

The Objective C compiler actually accepts this, and the advantage is that the signature can now be copy-pasted without modification between a .h and a .m file.

**Comment by leapfrog-bishalghimire** [comment]
Is there anyways we can change present style to a different one ? 
Other things are quite standard except this Method signature with semicolon at the end.
